# This is a basic workflow to help you get started with Actions

name: Copy files from S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push: branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.USER_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: us-east-1
      
      - name: Run a one-line script
        run: mkdir downloads
          
      - name: Run a one-line script
        run: |
          aws s3 cp s3://custom-gpu-sagemaker-image/installation/cudnn-9.0-linux-x64-v7.tgz ./downloads/ --recursive
          echo pwd
          
      - name: upload Artifacts
        uses: actions/upload-artifact@v2 
        with:
           name: assests-for-download
           path: downloads
